# Generated by Django 2.2.7 on 2019-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_timeperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UserPermissions', max_length=100)),
            ],
            options={
                'permissions': (('staff_add_book', 'Add Book'),),
                'default_permissions': (),
            },
        ),
    ]
